name: restApi

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: sysop
      POSTGRES_PASSWORD: sysop
      POSTGRES_DB: appdata  # Creates the "appdata" database if it doesn't exist
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data  # Data persistence in ./data/postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: sysop@admin.com
      PGADMIN_DEFAULT_PASSWORD: sysop
    ports:
      - "5000:80"

volumes:
  postgres_data: